version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
  frontend:
    container_name: tracker_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: tv-tracker/client
    env_file:
      - ./client/src/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  backend:
    container_name: tracker_server
    build:
      context: ./
      dockerfile: Dockerfile
    image: tv-tracker/server
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - db
    depends_on:
      - db
