version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
  frontend:
    container_name: tracker_front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: tv-tracker/frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
  backend:
    container_name: tracker_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: tv-tracker/server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    links:
      - db
    depends_on:
      - db
